from __future__ import annotations

from mailops.adapters.proton_bridge.networking import (
    bridge_host_candidates,
    is_wsl_environment,
    windows_host_from_default_route,
    windows_host_from_resolv_conf,
)


def test_is_wsl_environment_detects_env_marker(tmp_path) -> None:
    version_path = tmp_path / "version"
    version_path.write_text("Linux version 6.1.0\n", encoding="utf-8")

    assert is_wsl_environment(env={"WSL_DISTRO_NAME": "Ubuntu"}, version_path=version_path) is True


def test_windows_host_from_resolv_conf_returns_first_ipv4_nameserver(tmp_path) -> None:
    resolv_conf = tmp_path / "resolv.conf"
    resolv_conf.write_text(
        "\n".join(
            [
                "# generated by WSL",
                "nameserver 172.28.96.1",
                "search localdomain",
            ]
        ),
        encoding="utf-8",
    )

    assert windows_host_from_resolv_conf(resolv_conf) == "172.28.96.1"


def test_windows_host_from_default_route_decodes_little_endian_gateway(tmp_path) -> None:
    route = tmp_path / "route"
    route.write_text(
        "\n".join(
            [
                "Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT",
                "eth0\t00000000\t01601CAC\t0003\t0\t0\t0\t00000000\t0\t0\t0",
            ]
        ),
        encoding="utf-8",
    )

    assert windows_host_from_default_route(route) == "172.28.96.1"


def test_bridge_host_candidates_adds_wsl_windows_host_after_localhost(tmp_path) -> None:
    version_path = tmp_path / "version"
    resolv_conf = tmp_path / "resolv.conf"
    route = tmp_path / "route"
    version_path.write_text("Linux version 6.1.0-microsoft-standard-WSL2\n", encoding="utf-8")
    resolv_conf.write_text("nameserver 172.28.96.1\n", encoding="utf-8")
    route.write_text(
        "\n".join(
            [
                "Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT",
                "eth0\t00000000\t01601CAC\t0003\t0\t0\t0\t00000000\t0\t0\t0",
            ]
        ),
        encoding="utf-8",
    )

    assert bridge_host_candidates(
        "127.0.0.1",
        env={},
        version_path=version_path,
        resolv_conf_path=resolv_conf,
        route_path=route,
    ) == ["127.0.0.1", "172.28.96.1"]


def test_bridge_host_candidates_does_not_override_non_localhost(tmp_path) -> None:
    version_path = tmp_path / "version"
    version_path.write_text("Linux version 6.1.0-microsoft-standard-WSL2\n", encoding="utf-8")

    assert bridge_host_candidates("bridge.internal", env={}, version_path=version_path) == ["bridge.internal"]
